using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using PermitToWork.Application.Abstractions;

namespace PermitToWork.Infrastructure.Storage;

/// <summary>
/// Keeps uploaded files in a folder on disk.
/// <para>
/// Enough for this application, and deliberately behind <see cref="IFileStorage"/> so that
/// swapping it for object storage is one registration. Files are spread across
/// year/month subfolders — a single directory with tens of thousands of entries is slow to
/// list on every filesystem worth naming.
/// </para>
/// </summary>
internal sealed class LocalFileStorage : IFileStorage
{
    private readonly string _root;
    private readonly ILogger<LocalFileStorage> _logger;

    public LocalFileStorage(IConfiguration configuration, ILogger<LocalFileStorage> logger)
    {
        _logger = logger;
        _root = Path.GetFullPath(
            configuration["Storage:DocumentRoot"]
            ?? Path.Combine(AppContext.BaseDirectory, "uploads"));

        Directory.CreateDirectory(_root);
    }

    public async Task<string> SaveAsync(
        Stream content,
        string originalFileName,
        CancellationToken cancellationToken = default)
    {
        // The key is generated, never derived from what the browser sent. A file called
        // "..\..\appsettings.json" must not be able to decide where it lands, and the
        // extension is the only part of the original name worth keeping.
        var extension = Path.GetExtension(originalFileName);
        var folder = DateTimeOffset.UtcNow.ToString("yyyy/MM");
        var key = $"{folder}/{Guid.CreateVersion7()}{extension}";

        var path = ResolveWithinRoot(key);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        await using var file = File.Create(path);
        await content.CopyToAsync(file, cancellationToken);

        return key;
    }

    public Task<Stream?> OpenAsync(string storageKey, CancellationToken cancellationToken = default)
    {
        var path = ResolveWithinRoot(storageKey);

        if (!File.Exists(path))
        {
            // The row outliving its bytes is possible — a restored database, a wiped
            // folder — and is worth a log line rather than an exception at the caller.
            _logger.LogWarning("Document {Key} is recorded but its file is missing.", storageKey);
            return Task.FromResult<Stream?>(null);
        }

        return Task.FromResult<Stream?>(File.OpenRead(path));
    }

    public Task DeleteAsync(string storageKey, CancellationToken cancellationToken = default)
    {
        var path = ResolveWithinRoot(storageKey);

        if (File.Exists(path))
        {
            File.Delete(path);
        }

        return Task.CompletedTask;
    }

    /// <summary>
    /// Turns a key into a path, and refuses anything that would escape the root.
    /// <para>
    /// Keys are generated by this class, so in practice nothing malicious reaches here —
    /// but a path built from stored data is exactly the sort of thing that becomes
    /// user-controlled two refactors later, and the check costs nothing.
    /// </para>
    /// </summary>
    private string ResolveWithinRoot(string storageKey)
    {
        var path = Path.GetFullPath(Path.Combine(_root, storageKey));

        if (!path.StartsWith(_root, StringComparison.Ordinal))
        {
            throw new InvalidOperationException($"Storage key '{storageKey}' resolves outside the document root.");
        }

        return path;
    }
}
